### ISSUE TITLE
Beim Anlegen einer Entität mit einem Feld-Name "ID" wird ein Fehler geworfen

### ISSUE THREAD

**Issue by eddi888** [euu-rocks/seed#2]
Version: v0.9.18

Error-Message:
Reason: liquibase.exception.DatabaseException: FEHLER: Spalte ╗id½ mehrmals angegeben [Failed SQL: (0) CREATE TABLE public.ausgaben (id VARCHAR(255) NOT NULL, version INTEGER NOT NULL, createdon TIMESTAMP WITHOUT TIME ZONE, createdby VARCHAR(32), modifiedon TIMESTAMP WITHOUT TIME ZONE, modifiedby VARCHAR(32), id VARCHAR(255) NOT NULL, kategorie VARCHAR(255), datum date, betrag DOUBLE PRECISION, CONSTRAINT pk_sb PRIMARY KEY (id))]

Lösung:
Anlage von Felder mit folgenden Namen unterbinden:
id, version, createdon, createdby , modifiedon , modifiedby

**Comment by seed-master** [comment]
Field names are now checked against a blacklist.
