### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by zael84** [euu-rocks/seed#3]
Durch die README.md ist man nicht in der Lage seed zu starten.

1. Es wurde vergessen mvn clean install in der readme anzugeben. 
2. Wenn man keine DB auf localhost mit seed schema hat startet die Anwendung nicht, username und pw würden sicher weitere Probleme erzeugen.
3. dbc:postgresql://192.168.69.135:5432/seed" registry.digitalocean.com/euu/seed Caused by: java.net.SocketException: Network is unreachable (connect failed)
Ich vermute dafür muss man im VPN sein.

Vorschlag:
In der Readme.md eine Anleitung geben, durch die man mit 3-5 Befehlen einen seed server auf localhost starten kann, dazu sollte das Dockerfile um eine postgreDB erweitert werden, ggf. eignet sich dann docker-compose besser zum Bauen des Docker images.

**Comment by eddi888** [comment]
PR are welcome

**Comment by eddi888** [comment]
docker compose added
